name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build-${{ matrix.deno-version == 'canary' && 'canary' || 'release' }}-${{ matrix.unstable && 'unstable' || 'stable' }}-${{ matrix.no-check && 'nocheck' || 'tsc' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v1.x, canary]
        unstable: [false, true]
        no-check: [false, true]
    env:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno-version }}

      - uses: actions/checkout@v2

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint --unstable

      - name: Start elasticmq
        run: |
          docker-compose up -d
          sleep 5
          aws --endpoint-url "http://localhost:9324" sqs create-queue --queue-name test --region us-east-1 --attributes VisibilityTimeout=0

      - name: Test
        run: deno test --allow-net --allow-env${{ matrix.unstable && ' --unstable' || '' }}${{ matrix.no-check && ' --no-check' || '' }}
